apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
  labels:
    app: swiggy
    svc: dinein
    type: reserve-seat
spec:
  nodeSelector:
    node: worker1
  containers:
    - name: cont2
      image: srikanth0209/docker-volumes:reverse
      ports:
        - containerPort: 80
