apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: dWVvZWtodXY=
  CLOUDINARY_KEY: MTkyMjgxNjI2OTkzMzE0
  CLOUDINARY_SECRET: RXpKMHlMSE5SLTF5MmcxeWRlczJnUGFMeVBz
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljM0pwWVd0dWRHZzJOeUlzSW1FaU9pSmpiWFYyYVdGcGF6SXdNekpqTW5welpqUmhaMnh2Ylc1eEluMC5HMEF4bG11emNZUTlmbFcyN2hsNEl3
  DB_URL: bW9uZ29kYitzcnY6Ly9rb3RpcGFsbGlzcmlrYW50aDcxNTZfZGJfdXNlcjpUSnJjTVBIRUVVOWU4RjN6QGVrcy1tb25nb2RiLmF4Mmp1MmwubW9uZ29kYi5uZXQvP2FwcE5hbWU9RUtTLU1vbmdvREI=
