version: "3.9"

services:
  devopsdb:
    image: srikanth0209/project:db
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
        reservations:
          cpus: "0.2"
          memory: "512M"
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - mynetwork
    volumes:
      - DB:/opt/docker-stack

  application:
    image: srikanth0209/project:app
    ports:
      - "1111:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2048M"
        reservations:
          cpus: "0.5"
          memory: "1024M"
      replicas: 3
      restart_policy:
        condition: any
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
volumes:
  DB:
