version: "3.9"

services:
  devopsdb:
    image: srikanth0209/project:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
    networks:
      - mynetwork

  application:
    image: srikanth0209/project:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
